### ISSUE TITLE
Shadowrocket

### ISSUE THREAD

**Issue by hosseinc** [deathline94/SubLink-Worker#1]
It doesn't work with shadowrocket, I think it's because of the 64-bit  problem

**Comment by deathline94** [comment]
I will look into it ...

**Comment by hosseinc** [comment]
since using warp;//auto command with hiddify has become popular, for some reason if you put any link in the file, it won't return lines starting with warp ..

could you look into it?

**Comment by deathline94** [comment]
Actually , it does ! i've tested it myself and i can confirm it works ! these are my screenshots as you can see (sorry for the ugly drawings btw) :
take a look at your worker and make sure that you pasted the code in the right place.
![1](https://github.com/deathline94/SubLink-Worker/assets/11331137/dd51bf00-cc6c-4b2e-9c16-683276813cd1)
![2](https://github.com/deathline94/SubLink-Worker/assets/11331137/4945a5e8-fb1a-457c-ba1f-e4843f56a2c6)

**Comment by hosseinc** [comment]
My bad, it returns the warp command completely
