### ISSUE TITLE
اضافه کردن پنل در صورت امکان

### ISSUE THREAD

**Issue by gransa** [deathline94/SubLink-Worker#2]
سلام. ممنون بابت این کد.اگه میشه یه پنل بهش اضافه کنید تا دیگه نیاز نباشه هر دفعه کد ورکر رو مستقیم تغییر بدیم و بشه با موبایل ( که خودتون میدونید خیلی سخته کار با ورکر ) هم راحت کار کرد. بازم ممنون 🙏🙏🙏

**Comment by deathline94** [comment]
در اولین فرصت اضافه میکنم

**Comment by gransa** [comment]
> در اولین فرصت اضافه میکنم

خیلی لطف میکنید. مرسی🙏🙏

**Comment by gransa** [comment]
ممنونم. خیلی لطف کردی خیلی خیلی ممنونم 🙏🙏🙏
دو تا نکته :
یکی اینکه استیکرها رو تو ویتوری ان جی بصورت کاراکتر نشون میده![Screenshot_2024-09-30-02-58-46-134_com.android.chrome.jpg](https://github.com/user-attachments/assets/093cd699-64db-475f-8299-687432009d17)


میشه این:
![IMG_20240930_030623.jpg](https://github.com/user-attachments/assets/b79fe21d-aa67-4bf4-844c-ad5e9cc77bf6)




و اینکه امکان پیج کردن ندارد تا هر وقت آپدیت کردی. خودش آپدیت بشه ؟
بازم سپاس فراوان 🙏🙏🙏

**Comment by deathline94** [comment]
در مورد استیکر بررسی میکنم ببینم چه کار میشه کرد . ولی کانفیگ های کاستوم (مثل کانفیگ فرگمنت و کلا کانفیگ های json) ساپورت نمیشن . فقط کانفیگ های با url scheme مشخظ و یک خطی مثل vmess:// یا wireguard:// و امثال اینا رو داخل این سیستم میشه استفاده کرد

**Comment by gransa** [comment]
لطف میکنید 🙏 
تو پنل، کانفیگ با فرمت json ، هر خط رو جداگانه ثبت می‌کنه و معادل یه کانفیگ معمولی در نظر میگیره( مشابه اسکرین شات قبلی )، ولی وقتی لینک ساب رو داخل مرورگر باز می‌کنی ، درست نشون میده و داخل برنامه کار می‌کنه 🙂 ( مثلاً این فایل جیسون من، شامل ۱۵ کانفیگ بود و نزدیک به ۸۰۰۰ خط و بدون مشکل لود شد 👍 ). مشکل فقط همون استیکر بود که بهم ریخته بود. مرسی.🙏

**Comment by deathline94** [comment]
خیلی جالب شد پس . اصلا نیت همچین کاری و نداشتم ولی خب منطقیه :)) . چون هر خط رو جداگانه پرینت میکنه و v2ray میتونه راحت تفسیرش کنه . اگر وقت کنم ui بهتری براش درست میکنم در آینده . در مورد ایموجی هم همینطور

**Comment by gransa** [comment]
> خیلی جالب شد پس . اصلا نیت همچین کاری و نداشتم ولی خب منطقیه :)) . چون هر خط رو جداگانه پرینت میکنه و v2ray میتونه راحت تفسیرش کنه . اگر وقت کنم ui بهتری براش درست میکنم در آینده . در مورد ایموجی هم همینطور

😅آره مشکلی نداره ازون بابت ( یه json امتحان کنید ). بسیار سپاس از شما 🙏🙏🙏

**Comment by deathline94** [comment]
FIXED
